const dataProducts = [
  {
    name: "Cananga Oil",
    price: 456000,
    slug: "cananga-oil",
    quantity: 45,
    imageURL: "https://5.imimg.com/data5/SELLER/Default/2020/10/LT/LR/WY/23696507/ylang-ylang-oil.jpg",
    category: "Essential oil",
    olfactoryProfile: "Floral,fresh",
    description: "Cananga oil from west java",
  },
  {
    name: "Ginger Raw Material",
    price: 45000,
    slug: "ginger-raw-material",
    quantity: 67,
    imageURL: "https://qph.cf2.quoracdn.net/main-qimg-5432406cd48901f8a36c44fe43b28227",
    category: "Raw Material",
    olfactoryProfile: "punget",
    description: "Standar grade ginger Raw material",
  },
  {
    name: "Galangal Raw Material",
    price: 55000,
    slug: "galangal-raw-material",
    quantity: 60,
    imageURL: "https://prasetya.ub.ac.id/wp-content/uploads/2023/10/kencur.jpg",
    category: "Raw Material",
    olfactoryProfile: "spicy, earthy",
    description: "Premium grade galangal raw material, used in culinary and medicinal applications for its unique spicy aroma.",
  },
  {
    name: "Patchouli Oil",
    price: 120000,
    slug: "patchouli-oil",
    quantity: 30,
    imageURL: "https://www.norex.in/uploads/images/202209/img_1920x_6311bc23bea5a6-07376469-55481324.png",
    category: "Essential Oil",
    olfactoryProfile: "earthy, woody",
    description: "Pure patchouli essential oil, valued for its rich, earthy fragrance and calming properties.",
  },
  {
    name: "Clove Oil",
    price: 95000,
    slug: "clove-oil",
    quantity: 40,
    imageURL: "https://static.toiimg.com/thumb/msid-68182210,width-1280,height-720,resizemode-4/68182210.jpg",
    category: "Essential Oil",
    olfactoryProfile: "spicy, warm",
    description: "100% pure clove essential oil, known for its warm, spicy aroma and versatile uses in aromatherapy.",
  },
  {
    name: "Ginger Oil",
    price: 220000,
    slug: "ginger-oil",
    quantity: 45,
    imageURL: "https://www.norex.in/uploads/blog/202309/img_650bdce4886d77-20604922-48347065.jpg",
    category: "Essential oil",
    olfactoryProfile: "spicy, punget",
    description: "Ginger oil from central java",
  },
];
